apiVersion: v1
kind: Service
metadata:
  name: simple-fastapi
  namespace: simple-fastapi
spec:
  type: ClusterIP
  selector:
    app: simple-fastapi
  ports:
    - name: http
      port: 80
      targetPort: 8000